# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x0cidentra.auth\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"E\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"r\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\x12\x12\n\nexpires_in\x18\x05 \x01(\x03\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"[\n\x13VerifyTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\nexpires_at\x18\x04 \x01(\x03\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"Q\n\x14RefreshTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x03\x32\xc5\x02\n\x0b\x41uthService\x12I\n\x08Register\x12\x1d.identra.auth.RegisterRequest\x1a\x1e.identra.auth.RegisterResponse\x12@\n\x05Login\x12\x1a.identra.auth.LoginRequest\x1a\x1b.identra.auth.LoginResponse\x12R\n\x0bVerifyToken\x12 .identra.auth.VerifyTokenRequest\x1a!.identra.auth.VerifyTokenResponse\x12U\n\x0cRefreshToken\x12!.identra.auth.RefreshTokenRequest\x1a\".identra.auth.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=102
  _globals['_REGISTERRESPONSE']._serialized_start=104
  _globals['_REGISTERRESPONSE']._serialized_end=173
  _globals['_LOGINREQUEST']._serialized_start=175
  _globals['_LOGINREQUEST']._serialized_end=225
  _globals['_LOGINRESPONSE']._serialized_start=227
  _globals['_LOGINRESPONSE']._serialized_end=341
  _globals['_VERIFYTOKENREQUEST']._serialized_start=343
  _globals['_VERIFYTOKENREQUEST']._serialized_end=378
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=380
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=471
  _globals['_REFRESHTOKENREQUEST']._serialized_start=473
  _globals['_REFRESHTOKENREQUEST']._serialized_end=517
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=519
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=600
  _globals['_AUTHSERVICE']._serialized_start=603
  _globals['_AUTHSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
