# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vault_pb2 as proto_dot_vault__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/vault_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultServiceStub(object):
    """Vault service for secure key management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreKey = channel.unary_unary(
                '/identra.vault.v1.VaultService/StoreKey',
                request_serializer=proto_dot_vault__pb2.StoreKeyRequest.SerializeToString,
                response_deserializer=proto_dot_vault__pb2.StoreKeyResponse.FromString,
                _registered_method=True)
        self.RetrieveKey = channel.unary_unary(
                '/identra.vault.v1.VaultService/RetrieveKey',
                request_serializer=proto_dot_vault__pb2.RetrieveKeyRequest.SerializeToString,
                response_deserializer=proto_dot_vault__pb2.RetrieveKeyResponse.FromString,
                _registered_method=True)
        self.DeleteKey = channel.unary_unary(
                '/identra.vault.v1.VaultService/DeleteKey',
                request_serializer=proto_dot_vault__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=proto_dot_vault__pb2.DeleteKeyResponse.FromString,
                _registered_method=True)
        self.ListKeys = channel.unary_unary(
                '/identra.vault.v1.VaultService/ListKeys',
                request_serializer=proto_dot_vault__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=proto_dot_vault__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.KeyExists = channel.unary_unary(
                '/identra.vault.v1.VaultService/KeyExists',
                request_serializer=proto_dot_vault__pb2.KeyExistsRequest.SerializeToString,
                response_deserializer=proto_dot_vault__pb2.KeyExistsResponse.FromString,
                _registered_method=True)


class VaultServiceServicer(object):
    """Vault service for secure key management
    """

    def StoreKey(self, request, context):
        """Store a key securely
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveKey(self, request, context):
        """Retrieve a key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Delete a key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """List all key IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyExists(self, request, context):
        """Check if a key exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreKey': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreKey,
                    request_deserializer=proto_dot_vault__pb2.StoreKeyRequest.FromString,
                    response_serializer=proto_dot_vault__pb2.StoreKeyResponse.SerializeToString,
            ),
            'RetrieveKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveKey,
                    request_deserializer=proto_dot_vault__pb2.RetrieveKeyRequest.FromString,
                    response_serializer=proto_dot_vault__pb2.RetrieveKeyResponse.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=proto_dot_vault__pb2.DeleteKeyRequest.FromString,
                    response_serializer=proto_dot_vault__pb2.DeleteKeyResponse.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=proto_dot_vault__pb2.ListKeysRequest.FromString,
                    response_serializer=proto_dot_vault__pb2.ListKeysResponse.SerializeToString,
            ),
            'KeyExists': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyExists,
                    request_deserializer=proto_dot_vault__pb2.KeyExistsRequest.FromString,
                    response_serializer=proto_dot_vault__pb2.KeyExistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identra.vault.v1.VaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identra.vault.v1.VaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultService(object):
    """Vault service for secure key management
    """

    @staticmethod
    def StoreKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identra.vault.v1.VaultService/StoreKey',
            proto_dot_vault__pb2.StoreKeyRequest.SerializeToString,
            proto_dot_vault__pb2.StoreKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identra.vault.v1.VaultService/RetrieveKey',
            proto_dot_vault__pb2.RetrieveKeyRequest.SerializeToString,
            proto_dot_vault__pb2.RetrieveKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identra.vault.v1.VaultService/DeleteKey',
            proto_dot_vault__pb2.DeleteKeyRequest.SerializeToString,
            proto_dot_vault__pb2.DeleteKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identra.vault.v1.VaultService/ListKeys',
            proto_dot_vault__pb2.ListKeysRequest.SerializeToString,
            proto_dot_vault__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeyExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identra.vault.v1.VaultService/KeyExists',
            proto_dot_vault__pb2.KeyExistsRequest.SerializeToString,
            proto_dot_vault__pb2.KeyExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
